baseURL = "https://blog.ritikahotwani.com/"
title = ""

theme = "puppet"
# themesDir = "../.."

copyright = "2024 | Ritika Hotwani"
paginate = 5
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = false
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
# [[menu.main]]
# identifier = "guide"
# name = "Guide"
# url = "/series/themes-guide/"
# weight = 20
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
# [[menu.main]]
# identifier = "github"
# name = "Github"
# url = "https://github.com/roninro/hugo-theme-puppet/"
# weight = 100

# [params.gitalk]
# owner = "ritikahotwani"
# repo = "ritikahotwani-blog-comments"
# clientId = "B7ecbff3d7132216f424"
# clientSecret = "070d710906755e3e4bf6d6a56a5553196731aa32"

[params]
author = "Ritika Howani"
keywords = "blog,developer,personal"
img_home = "img/home-bg.png"
# img_home = "images/home/thanos-pal-cFbNlpRZKi0-unsplash.jpg"
img_404 = "img/404-bg.jpg"
images = ['img/home-bg.png']

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/memoji.jpeg"
bio = """

Hey there, I’m Ritika, a software developer based in Mumbai.

This is where I showcase my innovative projects and share my journey of crafting solutions that make a difference.

Welcome to my blog!

"""

[params.social]
rss_enable = true
twitter = "ritiii24"
instagram = "riti2.4"
# facebook = "johndoe"
# zhihu = "johndoe"
# weibo = "johndoe"
github = "ritikahotwani"
linkedin = "ritika-hotwani-46a651201/"
mail = "ritikahotwani24@gmail.com"

# [[params.friends]]
# name = "John Doe"
# url = "https://gohugo.io"

# [[params.friends]]
# name = "John Doe"
# url = "https://gohugo.io"

# See https://giscus.app/

[params.giscus]
enable = true
repo = "Chaitanya-Shahare/blog-site-comments"
repo_id = "R_kgDOIa6SGg"
# category = "General"
category = "Announcements"
category_id = "DIC_kwDOIa6SGs4CSgt4"
input_position = "top"
theme = "light_tritanopia"
lang = "en"